In [1]:
import torch
print(torch.__version__)

2.12.0


In [2]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    print(f"GPU is available and being used")
    print(f"Device name: {torch.cuda.get_device_name(device)}")
else:
    device = torch.device("cpu")

print(device)


cpu


In [13]:
#empty type
a = torch.empty(5, 3)
type(a)
torch.zeros(5, 3)
torch.rand(5, 3)
torch.manual_seed(42)
torch.randn(5, 3)
torch.tensor([[1, 2, 3], [4, 5, 6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [21]:
torch.arange(0,10,2)
torch.linspace(0,10,5)
torch.eye(5, 5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [23]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
x.shape

torch.Size([2, 3])

In [24]:
torch.empty_like(x)

tensor([[    140412375329704,      94027615797056,                   0],
        [                  0,                   0, 7310593858020254331]])

In [25]:
x.dtype

torch.int64

In [26]:
torch.tensor([1, 2, 3], dtype=torch.float32)

tensor([1., 2., 3.])

In [27]:
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [28]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])


In [29]:
a + b

tensor([5, 7, 9])

In [30]:
a - b

tensor([-3, -3, -3])

In [31]:
a * b

tensor([ 4, 10, 18])

In [32]:
torch.clamp(a, min=2, max=4)

tensor([2, 2, 3])

In [34]:
b = torch.tensor([[1, 2, 3], [4, 5, 6]])

In [35]:
b

tensor([[1, 2, 3],
        [4, 5, 6]])

In [38]:
torch.sum(b)
torch.sum(b, dim=0) # col
torch.sum(b, dim=1) # row

tensor([ 6, 15])

In [43]:
b = b.to(torch.float64)


In [44]:
torch.std(b)

tensor(1.8708, dtype=torch.float64)

In [46]:
torch.var(b)

tensor(3.5000, dtype=torch.float64)

In [47]:
torch.argmax(b)
torch.argmin(b)

tensor(0)

In [55]:
a = torch.randint(low=0, high=10, size=(3, 3))
b = torch.randint(low=0, high=10, size=(3, 3))
print(a)
print(b)
torch.matmul(a, b)

tensor([[0, 9, 0],
        [9, 6, 9],
        [5, 4, 8]])
tensor([[8, 6, 0],
        [0, 0, 0],
        [1, 3, 0]])


tensor([[ 0,  0,  0],
        [81, 81,  0],
        [48, 54,  0]])

In [56]:
a @ b

tensor([[ 0,  0,  0],
        [81, 81,  0],
        [48, 54,  0]])

In [57]:
torch.matmul(a, b)

tensor([[ 0,  0,  0],
        [81, 81,  0],
        [48, 54,  0]])

In [58]:
a

tensor([[0, 9, 0],
        [9, 6, 9],
        [5, 4, 8]])

In [60]:
a.T

tensor([[0, 9, 5],
        [9, 6, 4],
        [0, 9, 8]])

In [62]:
a = a.to(torch.float32)
torch.det(a)

tensor(-243.)

In [63]:
torch.inverse(a)

tensor([[-0.0494,  0.2963, -0.3333],
        [ 0.1111,  0.0000,  0.0000],
        [-0.0247, -0.1852,  0.3333]])

In [70]:
import time

size = 10000

matrix_cpu1 = torch.randn(size, size)
matrix_cpu2 = torch.randn(size, size)

# start = time.time()
# result_cpu = matrix_cpu1 @ matrix_cpu2
# end = time.time()
# print(f"Time taken: {end - start} seconds")

#Move to GPU
matrix_gpu1 = matrix_cpu1.to(device)
matrix_gpu2 = matrix_cpu2.to(device)

start = time.time()
matrix_gpu1 @ matrix_gpu2
end = time.time()
print(f"Time taken: {end - start:0.4f} seconds")

Time taken: 0.0002 seconds
